### ISSUE TITLE
Rendermodelslikecamera  to produce stereo views

### ISSUE THREAD

**Issue by tdowrick** [UCL/scikit-surgeryutils#20]
In GitLab by @ThomasDowrick on Mar 23, 2020, 18:07

Implement rendering of left/right views, rather than having to call the command twice.

**Comment by tdowrick** [comment]
In GitLab by @ThomasDowrick on Mar 23, 2020, 18:07

created merge request !11 to address this issue

**Comment by tdowrick** [comment]
In GitLab by @ThomasDowrick on Mar 23, 2020, 18:07

mentioned in merge request !11

**Comment by tdowrick** [comment]
In GitLab by @ThomasDowrick on Mar 26, 2020, 15:34

mentioned in commit b75b44a70ffef27907b61de53c10982c9d24e6a7

**Comment by tdowrick** [comment]
In GitLab by @ThomasDowrick on Mar 26, 2020, 15:52

mentioned in commit 532a8c06773b1009275f442c5906a37613ae442f

**Comment by tdowrick** [comment]
In GitLab by @ThomasDowrick on Mar 27, 2020, 20:27

mentioned in commit e7deab9a43b2c8e8b29b4555ad729d70d1ae6338

**Comment by tdowrick** [comment]
In GitLab by @ThomasDowrick on Jun 9, 2020, 18:45

mentioned in commit 0c931efbdd37aa8d43207ee5be61d376823ffa34

**Comment by MattClarkson** [comment]
I think this is done. Closing.
